# Generated by Django 5.0 on 2024-03-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=64)),
                ('version', models.IntegerField()),
                ('lastModified', models.DateTimeField()),
                ('modifications', models.TextField(default=None)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=64)),
                ('details', models.CharField(max_length=64)),
                ('belong_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='note.note')),
            ],
        ),
        migrations.CreateModel(
            name='collabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreatorOfTemplate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='templateUsed',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TemplateUsedis', to='note.template'),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('style', models.CharField(max_length=64)),
                ('IsBold', models.BooleanField(default=False)),
                ('IsItalic', models.BooleanField(default=False)),
                ('IsUnderline', models.BooleanField(default=False)),
                ('align', models.CharField(max_length=64)),
                ('belong_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='note.note')),
            ],
        ),
    ]
