# Generated by Django 5.0 on 2024-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='content',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
    ]
