# Generated by Django 5.0 on 2024-04-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_remove_diagram_collabs_diagram_collabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagram',
            name='label',
        ),
        migrations.DeleteModel(
            name='diagram_collabs',
        ),
    ]
